name: NCSNpp
target:
  _target_: dynamics_diffusion.sde_models.ncsnpp.NCSNpp
  scale_by_sigma: True
  ema_rate: 0.999
  normalization: 'GroupNorm'
  nonlinearity: 'swish'
  nf: 128
  ch_mult: [1,2,2,2]
  num_res_blocks: 4
  attn_resolutions: [16]
  resamp_with_conv: True
  conditional: True
  fir: True
  fir_kernel: [1, 3, 3, 1]
  skip_rescale: True
  resblock_type: 'biggan'
  progressive: 'none'
  progressive_input: 'residual'
  progressive_combine: 'sum'
  attention_type: 'ddpm'
  init_scale: 0.
  fourier_scale: 16
  conv_size: 3

  num_scales: 1000
  sigma_min: 0.01
  sigma_max: 50
  beta_min: 0.1
  beta_max: 20.
  dropout: 0.1
  embedding_type: 'fourier'

  image_size: 32
  num_channels: 3
  data_centered: False

  continuous: True