name: UNet
target:
  _target_: dynamics_diffusion.unet.create_unet_model
  image_size: 256
  num_channels: 256
  num_res_blocks: 2
  num_heads: 4
  num_heads_upsample: -1
  num_head_channels: 64
  attention_resolutions: "32,16,8"
  channel_mult: ""
  dropout: 0.0
  class_cond: False
  use_checkpoint: False
  use_scale_shift_norm: False
  resblock_updown: True
  use_fp16: True
  use_new_attention_order: False
  learn_sigma: False
