_target_: dynamics_diffusion.unet.create_unet_model
image_size: ${..dataset.image_size}
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
num_head_channels: 64
attention_resolutions: "16,8"
channel_mult: ""
dropout: 0.3
class_cond: ${..dataset.class_cond}
use_checkpoint: False
use_scale_shift_norm: False
resblock_updown: True
use_fp16: ${..use_fp16}
use_new_attention_order: False
learn_sigma: True
