name: UNet
target:
  _target_: dynamics_diffusion.unet.create_unet_model
  image_size: 64
  num_channels: 128
  num_res_blocks: 3
  num_heads: 4
  num_heads_upsample: -1
  num_head_channels: -1
  attention_resolutions: "16,8"
  channel_mult: ""
  dropout: 0.0
  class_cond: False
  use_checkpoint: False
  use_scale_shift_norm: True
  resblock_updown: False
  use_fp16: False
  use_new_attention_order: False
  learn_sigma: True
