_target_: dynamics_diffusion.script_util.create_gaussian_diffusion 
learn_sigma: ${..model.learn_sigma}
steps: 100
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: True
rescale_learned_sigmas: True