_target_: dynamics_diffusion.karras_diffusion.KarrasDenoiser
sigma_min: 0.002
sigma_max: 80.0
sigma_data: 0.5
weight_schedule: "uniform"
loss_norm: "l2"
distillation: ${karras_distillation:${..training_mode}}