defaults:
  - _self_
  - /model: MLP
  - /diffusion: gaussian
  - /dataset: maze2d-umaze 
_target_: dynamics_diffusion.sample_util.DDPMSampler
use_fp16: False
use_ddim: False
clip_denoised: False
num_samples: 24
batch_size: 4

