defaults:
  - _self_
  - /model: MLP
  - /diffusion: VPSDE
_target_: dynamics_diffusion.trainer_util.SDETrainer 
_recursive_: False

continuous: False
likelihood_weighting: False

total_training_steps: 1e6
batch_size: 1
microbatch: -1  # -1 disables microbatches

opt_name: "Adam"
lr: 1e-4
weight_decay: 0.0
lr_anneal_steps: 0
beta1: 0.9
eps: 1e-8
warmup: -1
grad_clip: -1

ema_rate: "0.9999"  # comma-separated list of EMA values
log_interval: 100
save_interval: 10000
resume_checkpoint: ""
use_fp16: False
fp16_scale_growth: 1e-3