defaults:
  - _self_
  - /model: MLP
  - /diffusion: VESDE
  - /dataset: kitchen-mixed 
_target_: dynamics_diffusion.train_util.SDETrainLoop

continuous: True
likelihood_weighting: False

total_training_steps: 1e6
batch_size: 16
microbatch: -1  # -1 disables microbatches

opt_name: "Adam"
lr: 1e-4
weight_decay: 0.0
lr_anneal_steps: 0
beta1: 0.9
eps: 1e-8
warmup: -1
grad_clip: -1

ema_rate: "0.9999"  # comma-separated list of EMA values
log_interval: 1000
save_interval: 10000
resume_checkpoint: ""
use_fp16: False # SDE does not support fp16
fp16_scale_growth: 1e-3