# @package _global_
env_name: Pendulum-v1
num_train_steps: 5000
eval_freq: 1000
# replay_buffer_capacity: 1e6

# Environment-specific overrides:
learn_temp:
  init_targ_entr: -2
  final_targ_entr: -2
  entr_decay_factor: 1.0

agent:
  horizon: 3
  warmup_steps: 500
