_target_: dynamics_diffusion.script_util.create_gaussian_diffusion 
learn_sigma: ${..model.learn_sigma}
steps: 4000
noise_schedule: "cosine"
timestep_respacing: "1000"
use_kl: True
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False