_target_: dynamics_diffusion.improved_unet.create_unet_model
image_size: ${..dataset.image_size}
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
attention_resolutions: "16,8"
dropout: 0.3
class_cond: ${..dataset.class_cond}
use_checkpoint: False
use_scale_shift_norm: True
learn_sigma: True
