defaults:
  - _self_
  - /dynamics/model@model: MLP
  - /dynamics/diffusion@diffusion: VPSDE
_target_: sacsvg.diffusion_dx.ScoreSDEDx
env_name: ${..env_name}
obs_dim: ${..obs_dim}
action_dim: ${..action_dim}
horizon: ${..agent.horizon}
detach_xt: true
clip_grad_norm: null
opt_name: "Adam"
lr: 1e-3
ema_rate: "0.9999"  # comma-separated list of EMA values
use_fp16: false
fp16_scale_growth: 1e-3

sde_continuous: true
sde_likelihood_weighting: false
sde_eps: 1e-8

sde_sampler:
  n_steps_each: 1
  noise_removal: True
  probability_flow: False
  snr: 0.16
  method: 'pc'
  predictor: 'reverse_diffusion'
  corrector: 'langevin'
  continuous: True