model_dir: ""
num_samples: 100
batch_size: 16
use_ema: False
clip_denoised: False
use_ddim: False
cm_sampler:
  generator: "determ"
  sampler: "heun"
  s_churn: 0.0
  s_tmin: 0.0
  s_tmax: .inf
  s_noise: 1.0
  steps: 40
  seed: 42
  ts: ""

hydra:
  run:
    dir: "${model_dir}/samples/${now:%Y%m%d-%H%M%S}"