defaults:
  - env: maze2d-large
  - trainer: ddpm
format_strs:
  - stdout
  - torch-tensorboard
global_batch_size: 2048
hydra:
  run:
    dir: ./logs/${hydra:runtime.choices.trainer}/${env.name}/${trainer.diffusion.name}/${trainer.model.name}/${now:%Y%m%d-%H%M%S}