defaults:
  - _self_
  - /model: UNet
  - /diffusion: gaussian
_target_: dynamics_diffusion.trainer_util.DDPMImageTrainer 
_recursive_: False
data_dir: "/home/matin/data2/dynamics_diffusion/cifar_train"
total_training_steps: 3e5
schedule_sampler: "loss-second-moment"
lr: 3e-4
weight_decay: 0.05
lr_anneal_steps: 0
batch_size: 256
microbatch: -1  # -1 disables microbatches
ema_rate: "0.9999"  # comma-separated list of EMA values
log_interval: 100 
save_interval: 10000
resume_checkpoint: ""
use_fp16: False
fp16_scale_growth: 1e-3
opt_name: "AdamW"