defaults:
  - _self_
  - trainer: ddpm
device: "cuda" # "cuda" or "cpu"
format_strs:
  - log
  - stdout
  - csv
  - tensorboard
hydra:
  run:
    dir: ./logs/${hydra:runtime.choices.trainer}/${get_runtime_choice:dataset}/${get_runtime_choice:diffusion}${sde_continuous_solver:${trainer}}/${get_runtime_choice:model}/${device}${oc.decode:${oc.env:WORLD_SIZE,1}}_${human_readable_steps:${trainer.total_training_steps}}_${now:%Y%m%d-%H%M%S}