defaults:
  - /dynamics_config/diffusion@diffusion: gaussian
  - /dynamics_config/model@model: MLP
_target_: sacsvg.diffusion_dx.DiffusionDx
_recursive_: False
env_name: ${env_name}
obs_dim: ${obs_dim}
action_dim: ${action_dim}
horizon: ${agent.horizon}
device: ${device}
detach_xt: true

clip_grad_norm: 1.0
ema_rate: "0.9999"  # comma-separated list of EMA values

lr: 1e-4

opt_name: "AdamW"
weight_decay: 0.0
schedule_sampler: "uniform"

learn_sigma: True