defaults:
  - env@_here_: mbpo_ant
  - dx: scoresdedx
tag: deploy

replay_buffer_capacity: min(${num_train_steps}, 1e6)
# replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 1000

eval_freq: ??? # Over-ridden by env
num_eval_episodes: 10
fixed_eval: false

pixels: false
normalize_obs: true

device: cpu
action_repeat: 1

log_freq: 10000
log_save_tb: true

save_video: false
delete_replay_at_end: true

save_freq: 100000
save_best_eval: true
save_zfill: 7

seed: 1

# For debugging:
num_initial_states: null # Use a subset of initial states
max_episode_steps: null # If set, use shorter episodes

model_free_hidden_dim: 512
model_free_hidden_depth: 4
obs_dim: ???
action_dim: ???
action_range: ???

agent:
  _target_: sacsvg.agent.SACSVGAgent
  env_name: ${env_name}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  action_range: ${action_range}
  device: ${device}
  # dx_cfg: ${dx}
  num_train_steps: ${num_train_steps}

  # temp_cfg: ${learn_temp}
  # temp_cfg: null # auto-set to best for env+agent if null

  # actor_cfg: ${normal_actor}
  actor_lr: 1e-4
  actor_betas: [0.9, 0.999]
  actor_update_freq: 1
  actor_mve: true
  actor_detach_rho: false
  actor_dx_threshold: null

  # critic_cfg: ${double_q_critic}
  critic_lr: 1e-4
  critic_tau: 0.005
  critic_target_update_freq: 1
  critic_target_mve: false
  full_target_mve: False

  discount: 0.99
  seq_batch_size: 1
  step_batch_size: 1024
  horizon: 3
  seq_train_length: ${agent.horizon}
  update_freq: 1

  model_update_freq: 1
  model_update_repeat: 1

  model_free_update_repeat: 1

  rew_hidden_dim: 512
  rew_hidden_depth: 2
  rew_lr: 1e-3

  done_hidden_dim: 512
  done_hidden_depth: 2
  done_lr: 1e-3
  done_ctrl_accum: true

  warmup_steps: 0 # Auto-set if null

  det_suffix: 0.0

  dx: ${dx}

  actor:
    _target_: sacsvg.actor.Actor
    obs_dim: ${obs_dim}
    action_dim: ${action_dim}
    hidden_dim: ${model_free_hidden_dim}
    hidden_depth: ${model_free_hidden_depth}
    log_std_bounds: [-5, 2]

  critic:
    _target_: sacsvg.critic.DoubleQCritic
    obs_dim: ${obs_dim}
    action_dim: ${action_dim}
    hidden_dim: ${model_free_hidden_dim}
    hidden_depth: ${model_free_hidden_depth}

  temp:
    _target_: sacsvg.temp.LearnTemp
    init_temp: 0.1
    max_steps: ${num_train_steps}
    init_targ_entr: -${action_dim}
    final_targ_entr: -${action_dim}
    entr_decay_factor: 0.
    only_decrease_alpha: false
    lr: 1e-4
    device: ${device}

hydra:
  searchpath:
    - file://config
  run:
    dir: ./logs/${tag}/sacsvg/${env_name}/${split:${agent.dx._target_}}/${now:%Y%m%d-%H%M%S} 