_target_: dynamics_diffusion.script_util.create_gaussian_diffusion 
learn_sigma: False
steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False