defaults:
  - _self_
  - trainer: ddpm_image
format_strs:
  - stdout
  - torch-tensorboard
tag: deploy
hydra:
  run:
    dir: ./logs/${tag}/${hydra:runtime.choices.trainer}/${trainer.diffusion.name}/${trainer.model.name}/${now:%Y%m%d-%H%M%S}